import {StyleSheet, Dimensions} from 'react-native';
import {RFValue} from 'react-native-responsive-fontsize';
import {Colors, FONTS} from 'styles';
const {width} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    height: width * 1.4,
    width: '100%',
    position: 'absolute',
    bottom: 0,
    backgroundColor: Colors.WHITE,
    borderTopEndRadius: width * 0.05,
    borderTopStartRadius: width * 0.05,
    paddingHorizontal: width * 0.04,
  },
  invoice: {
    width: '100%',
    height: width * 0.8,
    backgroundColor: Colors.WHITE,
    marginTop: -width * 0.25,
    borderRadius: width * 0.03,
    borderWidth: 1,
    borderColor: Colors.LINE_STROKE,
    borderStyle: 'dashed',
  },
  invoicedate: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: Colors.LINE_STROKE,
    borderStyle: 'dashed',
    height: width * 0.11,
    alignItems: 'center',
    paddingHorizontal: width * 0.04,
  },
  noinvoice: {
    flex: 1,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(12),
    color: Colors.LIGHT_TEXT,
  },
  date: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(12),
    color: Colors.LIGHT_TEXT,
  },
  detailinvoice: {
    width: '100%',
    height: '100%',
    paddingHorizontal: width * 0.04,
  },
  waitinglabel: {
    flexDirection: 'row',
    marginVertical: width * 0.02,
  },
  iconsection: {
    width: 17,
    height: 17,
    backgroundColor: Colors.ORANGE,
    borderRadius: width * 0.1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  icon: {
    color: Colors.WHITE,
    fontSize: RFValue(14),
  },
  textwaiting: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(10),
    marginTop: width * 0.003,
    marginHorizontal: width * 0.015,
    color: Colors.LIGHT_TEXT,
  },
  nameroom: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(12),
    color: Colors.BLACK,
    marginVertical: width * 0.0012,
  },
  labelreceived: {
    flexDirection: 'row',
    marginTop: width * 0.05,
  },
  textreceived: {
    flex: 1,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(13),
    color: Colors.DRAKER_BLACK,
  },
  textnamereceived: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(13),
    color: Colors.DRAKER_BLACK,
  },
  labeltotal: {
    flexDirection: 'row',
    width: '100%',
    height: 36,
    backgroundColor: 'rgba(31, 184, 252, 0.1)',
    alignItems: 'center',
    paddingHorizontal: width * 0.04,
    borderRadius: width * 0.02,
    marginVertical: width * 0.013,
  },
  texttotal: {
    flex: 1,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(13),
    color: Colors.DRAKER_BLACK,
  },
  totalnumber: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(13),
    color: Colors.DRAKER_BLACK,
  },
  textfromrek: {
    fontFamily: FONTS.poppins[500],
    color: Colors.LIGHT_TEXT,
    fontSize: RFValue(13),
    marginTop: width * 0.02,
  },
  accountsection: {
    flexDirection: 'row',
    marginVertical: width * 0.01,
  },
  leftsection: {
    flex: 1,
  },
  rightsection: {
    alignItems: 'flex-end',
  },
  textaccount: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(13),
    color: Colors.DRAKER_BLACK,
  },
  proofsection: {
    width: '100%',
    alignItems: 'center',
    flex: 1,
  },
  textproof: {
    marginTop: width * 0.04,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(13),
    color: Colors.LIGHT_TEXT,
  },
  img: {
    marginTop: width * 0.01,
    width: width * 0.92,
    height: width * 0.4,
    borderRadius: width * 0.01,
  },
  btnsection: {
    flexDirection: 'row',
    width: '100%',
    marginVertical: width * 0.03,
    justifyContent: 'center',
  },
  rejectbtn: {
    width: width * 0.45,
    height: width * 0.12,
    borderWidth: 1,
    borderColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width * 0.025,
    marginHorizontal: width * 0.01,
  },
  textrejectbtn: {
    color: Colors.PRIMARY,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(14),
    marginTop: width * 0.005,
  },
  receivedbtn: {
    width: width * 0.45,
    height: width * 0.12,
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width * 0.025,
    marginHorizontal: width * 0.01,
  },
  textreceivedbtn: {
    color: Colors.WHITE,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(14),
    marginTop: width * 0.005,
  },
  containermodal: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentmodal: {
    width: width * 0.9,
    height: width * 0.78,
    backgroundColor: Colors.WHITE,
    marginHorizontal: width * 0.04,
    borderRadius: width * 0.04,
    padding: width * 0.04,
  },
  textmodal: {
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(14),
    color: Colors.BLACK,
    marginBottom: width * 0.012,
  },
  inputsection: {
    height: width * 0.4,
    borderWidth: 1,
    borderColor: Colors.LINE_STROKE,
    borderRadius: width * 0.03,
    paddingHorizontal: width * 0.03,
    marginBottom: width * 0.08,
  },
  inputmodal: {
    fontFamily: FONTS.poppins[500],
    color: Colors.DRAKER_BLACK,
    fontSize: RFValue(12),
  },
  rejectbtnmodal: {
    width: width * 0.4,
    height: width * 0.11,
    borderWidth: 1,
    borderColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width * 0.025,
    marginHorizontal: width * 0.01,
  },
  receivedbtnmodal: {
    width: width * 0.4,
    height: width * 0.11,
    backgroundColor: Colors.PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: width * 0.025,
    marginHorizontal: width * 0.01,
  },
  textrejectbtnmodal: {
    color: Colors.PRIMARY,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(12),
    marginTop: width * 0.005,
  },
  textreceivedbtnmodal: {
    color: Colors.WHITE,
    fontFamily: FONTS.poppins[500],
    fontSize: RFValue(12),
    marginTop: width * 0.005,
  },
});
